### ISSUE TITLE
Could not parse license message

### ISSUE THREAD

**Issue by captaindooley** [devine-dl/pywidevine#50]
I fully admit, I'm out of my depth here, but I have my CDM and wvd file, I know where to find PSSH and the licensing URL, and I was successfully able to pull keys from bitmovin and tg4.ie as tests... but when I went to pull from a live site I wanted the video from I got a "Could not parse license_message as a SignedMessage, Error parsing message" response.

I also noticed that the PSSH value was MUCH longer than both of my test sites...

What am I doing wrong?

Full response here:

```
INFO:root:pywidevine version 1.8.0 Copyright (c) 2022-2024 rlaphoenix
INFO:root:https://github.com/devine-dl/pywidevine
INFO:license:[+] Loaded Device (7283 L3)
INFO:license:[+] Loaded CDM
INFO:license:[+] Opened CDM Session: 2438e9eb69e80503839dbad22c8e3282
INFO:license:[+] Created License Request Message (Challenge)
INFO:license:[+] Got License Message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywidevine/cdm.py", line 407, in parse_license
    signed_message.ParseFromString(license_message)
google.protobuf.message.DecodeError: Error parsing message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/pywidevine", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywidevine/main.py", line 116, in license_
    cdm.parse_license(session_id, licence)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pywidevine/cdm.py", line 411, in parse_license
    raise InvalidLicenseMessage(f"Could not parse license_message as a SignedMessage, {e}")
pywidevine.exceptions.InvalidLicenseMessage: Could not parse license_message as a SignedMessage, Error parsing message
```

**Comment by ApeDevOne** [comment]
I'm also facing same problem. I believe it's because some services has changed their licence url and the token gets invalid as soon as it's used. Still needs to be investigated.

**Comment by ApeDevOne** [comment]
This happens because token is one  time token or it is expiring. 
Basic code will not work. You have to write your own code. 

Refer to []()https://forum.videohelp.com/threads/411862-Beyond-WKS-KEYS this link. 

There's a code which worked for me. I have different codes written for different sites.

**Comment by R4H4T069** [comment]
i tried Crunchyroll But Show Me This error

Traceback (most recent call last):
  File "C:\Users\mdrah\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywidevine\cdm.py", line 407, in parse_license
    signed_message.ParseFromString(license_message)
google.protobuf.message.DecodeError: Error parsing message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mdrah\OneDrive\Documents\Widevine\key.py", line 42, in <module>
    cdm.parse_license(session_id, licence.content)
  File "C:\Users\mdrah\AppData\Local\Programs\Python\Python312\Lib\site-packages\pywidevine\cdm.py", line 411, in parse_license
    raise InvalidLicenseMessage(f"Could not parse license_message as a SignedMessage, {e}")
pywidevine.exceptions.InvalidLicenseMessage: Could not parse license_message as a SignedMessage, Error parsing message

C:\Users\mdrah\OneDrive\Documents\Widevine>

**Comment by ApeDevOne** [comment]
Common wv won't work on crunchyroll. Crunchyroll uses DRMtoday. Wks-keys had code for DRMtoday. Try finding it.

**Comment by Sovenok-Hacker** [comment]
The same on Kinescope:
```
11:35:51 owl@PC kinedl → pywidevine license device-Karoolus.wvd "AAAAbnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAE4SIDM2NjE3NTY1Nzg1MDRkNDI1ZjUyNzA2ZjcxNDE3MzNkIiQ2MjY1OGZjZi00OGYzLTRjYTUtYjk4OC1mNTRlMDg4NWY2MTVI88aJmwY=" "https://license.kinescope.io/v1/vod/62658fcf-48f3-4ca5-b988-f54e0885f615/acquire/widevine?token="
INFO:root:pywidevine version 1.9.0 Copyright (c) 2022-2026 rlaphoenix
INFO:root:https://github.com/devine-dl/pywidevine
INFO:license:[+] Loaded Device (4464 L3)
INFO:license:[+] Loaded CDM
INFO:license:[+] Opened CDM Session: 5e75a79ac6e05dda2fb0148fc85438f1
INFO:license:[+] Created License Request Message (Challenge)
INFO:license:[+] Got License Message
Traceback (most recent call last):
  File "/home/owl/.local/lib/python3.14/site-packages/pywidevine/cdm.py", line 407, in parse_license
    signed_message.ParseFromString(license_message)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
google.protobuf.message.DecodeError: Error parsing message with type 'pywidevine_license_protocol.SignedMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owl/.local/bin/pywidevine", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/owl/.local/lib/python3.14/site-packages/click/core.py", line 1514, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/owl/.local/lib/python3.14/site-packages/click/core.py", line 1435, in main
    rv = self.invoke(ctx)
  File "/home/owl/.local/lib/python3.14/site-packages/click/core.py", line 1902, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/owl/.local/lib/python3.14/site-packages/click/core.py", line 1298, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/owl/.local/lib/python3.14/site-packages/click/core.py", line 853, in invoke
    return callback(*args, **kwargs)
  File "/home/owl/.local/lib/python3.14/site-packages/pywidevine/main.py", line 116, in license_
    cdm.parse_license(session_id, licence)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/owl/.local/lib/python3.14/site-packages/pywidevine/cdm.py", line 411, in parse_license
    raise InvalidLicenseMessage(f"Could not parse license_message as a SignedMessage, {e}")
pywidevine.exceptions.InvalidLicenseMessage: Could not parse license_message as a SignedMessage, Error parsing message with type 'pywidevine_license_protocol.SignedMessage'
